---
title: "Data analysis I: Basics (preparation)"
author: "Tuomas Eerola"
date: "22/11/2021"
output: 
  pdf_document
urlcolor: blue
documentclass: article
classoption: a4paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R_template and tutorial in R (Data analysis I: Basics)

This session assumes that you have

* _RStudio_
* A basic understanding of _RStudio_ workspace, path, and environment (you can browse through _Chapter 6.5 in Scientific Musicology_ for these basics).

* Materials downloaded from [https://github.com/tuomaseerola/R_template](https://github.com/tuomaseerola/R_template)

  * Tip 1: use the green “Code” button to “Download zip” file at Github
  * Tip 2: extract this into a convenient location on your computer and open contents.R with _RStudio_. 

* You have read the [R_Template](https://github.com/tuomaseerola/R_template) page and perhaps had a quick peak at the rendered version of the page [https://tuomaseerola.github.io/R_template/](https://tuomaseerola.github.io/R_template/).

## Aims

1. Check the setup of your _RStudio_
2. Reading data into _R_ (tsv and Excel)
3. Look at the pre-processing steps aimed for poorly formatted file from downloaded from _Qualtrics_. 
  - filter some variables and some observations
  - turn categorical variables into factors
  - convert into long-format from wide-format
4. Summarise some properties of the data (descriptives and plotting)

There will be tasks for you to do. The scripts should work by if you have the right libraries and you run the script in the right environment.

